### ISSUE TITLE
TypeError: migrationCreator is not a function

### ISSUE THREAD

**Issue by rachel-church** [contentful/contentful-migration#103]
Running the below command caused a TypeError
`contentful-migration --space-id 3mu3dzx76r6a migrations/change-country-field.js`

`contentful-migration --version` => 0.9.0

```
TypeError: migrationCreator is not a function
    at /usr/local/lib/node_modules/contentful-migration/built/lib/migration-steps/index.js:139:16
    at tryCatcher (/usr/local/lib/node_modules/contentful-migration/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/usr/local/lib/node_modules/contentful-migration/node_modules/bluebird/js/release/method.js:39:29)
    at Object.migration (/usr/local/lib/node_modules/contentful-migration/built/lib/migration-steps/index.js:138:23)
    at migration (/usr/local/lib/node_modules/contentful-migration/built/lib/migration-parser.js:43:49)
    at run (/usr/local/lib/node_modules/contentful-migration/built/bin/cli.js:53:29)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-migration/bin/contentful-migration:6:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by Khaledgarbaya** [comment]
Hi @rachel-church,
I will investigate this and get back to you asap.

Khaled

**Comment by Khaledgarbaya** [comment]
Hi @rachel-church,
I was able to reproduce this issue, what was your node version?
Best,
Khaled

**Comment by rachel-church** [comment]
I have node v8.9.4

**Comment by Khaledgarbaya** [comment]
Hey @rachel-church sorry I missed the not in my previous comment, does removing and installing the package again help ?

**Comment by Khaledgarbaya** [comment]
I closing this issue due to inactivity, feel free to create a new one if needed

**Comment by chrisdobler** [comment]
I'm getting the same error. It's not clear what causes it. @Khaledgarbaya do you have any idea what might be set wrong? The cli works fine.
