### ISSUE TITLE
"Expected parameter accessToken" error when chaining migrations

### ISSUE THREAD

**Issue by szimek** [contentful/contentful-migration#104]
I'm trying to use https://github.com/tj/node-migrate to run migrations for multiple spaces. However, when I try to chain migrations, I'm getting this error after the first migration is executed:
```
(node:28850) UnhandledPromiseRejectionWarning: TypeError: Expected parameter accessToken
    at createClient (/Users/.../node_modules/contentful-migration/node_modules/contentful-management/dist/contentful-management.node.js:2541:11)
    at Object.createManagementClient (/Users/.../node_modules/contentful-migration/built/bin/lib/contentful-client/index.js:47:12)
    at run (/Users/.../node_modules/contentful-migration/built/bin/cli.js:42:40)
    ...
```

Here's a simplified version of the code I'm trying to run:
```js
const migrate = require('contentful-migration/built/bin/cli').default;

const options = {
  filePath,
  environmentId: 'development',
  yes: true,
};

migrate({ ...options, spaceId: 'some-id' })
  .then(() => migrate({ ...options, spaceId: 'some-other-id' }))
  .then(() => {
    console.log('Finished all migrations');
  });
```
The first migration completes successfully and then this error is thrown. 

I've got my `cmaToken` stored in `~/.contentfulrc.json` file, so I don't pass `accessToken` with each call.

**Comment by Khaledgarbaya** [comment]
Hi @szimek,
Do you still have this issue?

**Comment by Khaledgarbaya** [comment]
This issue had no activity for some time now, please feel free to create a new one if you still have the issue
