### ISSUE TITLE
Transform Entries should not publish if the source entry is a draft

### ISSUE THREAD

**Issue by gburgett** [contentful/contentful-migration#105]
I'm writing a migration to rename a field in a content type, and doing a transformation to copy the value over.  Unfortunately when I do so, the "Transform Entries" step also runs over a draft entry and then tries to publish it.  This entry is not yet valid due to other fields that have nothing to do with the migration.

**Expected behavior:**
The migration should publish the transformation for any entries that are already published.  It should not publish drafts.

**Actual behavior:**
```
The following migration has been planned

Update Content Type section-hero

  Create field style
    - name: "Style"
    - type: "Symbol"
    - localized: false
    - required: false
    - validations: [{"in":["default","large"]}]
    - disabled: false
    - omitted: false

Publish Content Type section-hero
Transform entries for section-hero
  - from: styles
  - to: style
Update Content Type section-hero

  Delete field styles

Publish Content Type section-hero
Update editor interface for Content Type section-hero

  Update field style
    - widgetId: "dropdown"
    - helpText: "Choose one of the available styles for this Section."
? Do you want to apply the migration Yes
 ✔ Update Content Type section-hero
 ❯ Transform entries for section-hero
   ✖ Making requests (6/6)
     → Batch failed
   Update Content Type section-hero
   Update editor interface for Content Type section-hero
🚨  Migration unsuccessful
Batch failed

Error: {"status":"Unprocessable Entity","message":"Validation error","details":{"errors":[{"name":"required","path":["fields","text"],"details":"The property \"text\" is required here"}]},"url":"https://api.contentful.com:443/spaces/xxxx/environments/xxxx/entries/xxxx/published"}
```

Relevant log entry:
```
InvalidEntry: {
  "status": 422,
  "statusText": "Unprocessable Entity",
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "required",
        "path": [
          "fields",
          "text"
        ],
        "details": "The property \"text\" is required here"
      }
    ]
  },
  "request": {
    "url": "https://api.contentful.com:443/spaces/xxxx/environments/xxxx/entries/xxxx/published",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "app contentful.migration-cli/0.8.0; sdk contentful-management.js/5.0.0-beta2; platform node.js/v8.4.0; os macOS/16.7.0;",
      "Authorization": "Bearer ...",
      "user-agent": "node.js/v8.4.0",
      "Accept-Encoding": "gzip",
      "X-Contentful-Version": 2,
      "X-Contentful-Content-Type": "section-hero"
    },
    "method": "put"
  },
  "requestId": "412632edbef61d38f2f6aaa5b4dca13a"
}
    at errorHandler (./node_modules/contentful-migration/node_modules/contentful-management/dist/webpack:/contentfulManagement/error-handler.js:60:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

Thanks for all your hard work!  Overall it's a great tool.

**Comment by Khaledgarbaya** [comment]
Hi @gburgett,
Thanks for reporting this we'll take care of this as soon as possible.

Khaled

**Comment by aKzenT** [comment]
We had a similar problem with the new transformEntryToType action in our pull request. We solved it by making the publish-option tristate true/false/"preserve". When configured with "preserve" it will keep the original state of the source entry. Maybe a similar solution could be used for this action as well.

**Comment by jesustalaveragomez** [comment]
Hi, what's the status of this issue? 
We would like to use the deriveLinkedEntries feature, but our migrations fail because of draft contents

**Comment by TimBeyer** [comment]
This has been fixed in https://github.com/contentful/contentful-migration/pull/143 by adding the `'preserve'` option to the transform action.
