### ISSUE TITLE
"migrationCreator is not a function" when using contentful-migration "runMigration"

### ISSUE THREAD

**Issue by alex-greco-harrys** [contentful/contentful-migration#124]
## Expected Behavior

-The contentful-migration library should work as described in readme file.
-The runMigration command should run the multiple migration scripts.

## Actual Behavior

```
`mbpus0477hsra18:<DIR> <USUR_NAME>$ contentful space migration --space-id <SPACE_ID> scripts/contentful-migrations/migration_runner.js 

TypeError: migrationCreator is not a function
    at /Users/<USUR_NAME>/.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/node_modules/contentful-migration/built/lib/migration-steps/index.js:139:16
    at tryCatcher (/Users/<USUR_NAME>/.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/Users/<USUR_NAME>/.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/method.js:39:29)
    at Object.migration (/Users/<USUR_NAME>/.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/node_modules/contentful-migration/built/lib/migration-steps/index.js:138:23)
    at migration (/Users/<USUR_NAME>/.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/node_modules/contentful-migration/built/lib/migration-parser.js:43:49)
    at run (/Users/<USUR_NAME>/.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/node_modules/contentful-migration/built/bin/cli.js:53:29)
    at exports.migration (/Users/<USUR_NAME>/.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/dist/cmds/space_cmds/migration.js:82:28)
    at <anonymous>
`
```

```
const runMigration = require('contentful-migration/built/bin/cli').default;
const path = require('path');

const options = {
  spaceId: '<SPACE_ID>',
  accessToken:
    '<TOKEN>',
  yes: true,
};

const migrations = async () => {
  await runMigration({
    ...options,
    ...{
      filePath: path.join(__dirname, '<FILE_PATH>'),
    },
  });

  await runMigration({
    ...options,
    ...{ filePath: path.join(__dirname, '<FILE_PATH>') },
  });

  await runMigration({
    ...options,
    ...{ filePath: path.join(__dirname, '<FILE_PATH>') },
  });

  await runMigration({
    ...options,
    ...{ filePath: path.join(__dirname, '<FILE_PATH>') },
  });
};

migrations();
```

## Steps to Reproduce

1. Run the script in the console

## Context

I am unable to run the migration scripts in order. The error that is provided is not very helpful and seems to be an internal application error.

## Environment

-   **Node Version**: 9.11.1
-   **Package Manager Version**: 5.6
-   **Operating System**: MAC OS 10.13.5
-   **Package Version**:   "contentful-migration": "^0.10.0",

**Comment by axe312ger** [comment]
Thank you, we will have a look

**Comment by alex-greco-harrys** [comment]
Has there been any discovery or progress with this issue? @axe312ger @Khaledgarbaya

**Comment by Khaledgarbaya** [comment]
Hey @alex-greco-harrys I was not able to reproduce the issue. Did you make sure that your migration files exist and has no error?
Can you share your migration code? OR can you isolate this problem in a small repo so I can take a look at?

**Comment by zcei** [comment]
`runMigration` is not intended to be used with the contentful-cli runner. The CLI actually uses `runMigration` to do the migration. For that it needs to receive a function (what you export from the migration file).

Your "migration file" is a simple on-off method call. Nothing is exported, so nothing can be run. 
Agreed, the error message could be a bit nicer.

Out of curiosity: where did you get the impression from, that you could do such thing with the `contentful-cli` and our migration tooling?

**Comment by alex-greco-harrys** [comment]
@zcei I will look into your suggestions and keep you updated on my progress. 

As for where I got this approach, I looked at the following example on this [page](https://github.com/contentful/contentful-migration)

```
const runMigration = require('contentful-migration/built/bin/cli').default

const options = {
  spaceId: '<space-id>',
  accessToken: '<access-token>',
  yes: true
}

const migrations = async () => {
  await runMigration({...options, ...{filePath: '01-angry-dog.js'}})
  await runMigration({...options, ...{filePath: '02-friendly-dog.js'}})
  await runMigration({...options, ...{filePath: '03-long-example.js'}})
  await runMigration({...options, ...{filePath: '04-steps-errors.js'}})
  await runMigration({...options, ...{filePath: '05-plan-errors.js'}})
  await runMigration({...options, ...{filePath: '06-delete-field.js'}})
  await runMigration({...options, ...{filePath: '07-display-field.js'}})
}

migrations()
```

```
// Basic example: create new content type.
module.exports = function (migration) {
  const dog = migration.createContentType('dog', {
    name: 'angry dog',
    description: 'super angry'
  });

  dog.createField('woofs', {
    name: 'woof woof',
    type: 'Number',
    required: true
  });
};
```

**Comment by chrisdobler** [comment]
I'm getting the exact same error. It works in the cli and not in the code with the provided examples.

**Comment by Khaledgarbaya** [comment]
This issue had no activity for some time now, please feel free to create a new one if you still have the issue
