### ISSUE TITLE
Migration is failing intermittently due to `SpaceAccessError`

### ISSUE THREAD

**Issue by hariprasadr-tw** [contentful/contentful-migration#1309]
## Expected Behavior

Contentful migrations execution should be <mark>**consistently successful**</mark> when migration function is correct and valid.

## Actual Behavior

Contentful migration is <mark>**failing intermittently**</mark> even though the migration function is correct and valid. It always throws general error message 

```shell
🚨  Migration unsuccessful
The provided space does not exist or you do not have access.

🚨  Migration unsuccessful
Error: The provided space does not exist or you do not have access.

🚨  Migration unsuccessful
    at run (/******<masked-file-path>/node_modules/contentful-migration/src/bin/cli.ts:141:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

> Should bubble up the exact error message instead of throwing general error message for any error scenarios.

**Note:**
- This happens only on running migrations in CI pipeline (Azure DevOps). [*linux x64*]
  > **It is successful after running CI Pipeline for multiple attempts (more than 4 or 5 times) without any changes.**
- This is working fine always in our local machine. [*Windows Server 2019*]
- We are 100% sure about the correctness of SpaceID, EnvironmentID, Host URL, AccessToken being used in both CI pipeline and local machine.

## Steps to Reproduce

1. Failing **intermittently** on executing `runMigration` method from `contentful-migration` library
2. We tried with multiple configuration options for `runMigration` method. Still this issue remains same.
3. Before executing `runMigration` method in code, we also tried to get some content entries using ManagementClient (`content-management`) approach with same `configOptions` and it is always successful and returns correct value in all cases.
4. Also, executed Contentful CLI space/env commands and it is always successful and returns correct value. We don't want `contentful-migration` CLI commands to run our migrations.
5. To conclude, problem lies only with `runMigration` method.

```typescript
  import Migration, { runMigration, RunMigrationConfig } from "contentful-migration";

  export type MigrationExecutor = (migration: Migration) => void;

  // here migrations.Executors is of type 'MigrationExecutor[]'
  for (var executor of migrations.Executors) {

    await runMigration({
      ...this.configOptions,
      migrationFunction: (migration: Migration) => {
      	executor(migration); // Example: This will call dog.ts methods(up/down) based on reference in `executor`
      }
    })
    .then(() => {
    	sequenceNumber += 1;
    	console.log(`\nMigration done for (${sequenceNumber}).`);
    })
    .catch((e) => {
    	console.error(e);
    	isSuccess = false;
    	throw new Error(e);
    });
  }
  if (isSuccess) {    
    await this.updateVersion(migrations.targetVersion);
  }

  const siteName: string = "xyz";
  const configOptions: Partial<RunMigrationConfig> = {
      host: env[`CONTENTFUL_API_URL`], // api.eu.contentful.com
      spaceId: env[`${siteName}_SPACE_ID`], // Getting values from environmental variables, verified correctness in CI
      accessToken: env[`${siteName}_ACCESS_TOKEN`], // Getting values from environmental variables, verified correctness in CI 
      environmentId: env[`${siteName}_ENV_ID`], // Getting values from environmental variables, verified correctness in CI 
      requestBatchSize: 15, // Also tried for different values 50, 30, [without this option]
      requestLimit: 7, // Also tried for different values 8, [without this option]
      retryLimit: 10, // Also tried for different values 5, [without this option]
      yes: true
    }
```
```typescript
  // dog.ts // simple migration steps
  import Migration from 'contentful-migration';

  export type MigrationMethod = {
      up: MigrationExecutor;
      down: MigrationExecutor;
  };
  const dogContentTypeId = 'dog';

  function up(migration: Migration): void {
      const dog = migration.createContentType(dogContentTypeId, {
          name: 'Dog'
      });
      const name = dog.createField('name')
      name.name('Name').type('Symbol').required(true);
  }

  function down(migration: Migration): void {
      migration.deleteContentType(dogContentTypeId);
  }

  const migrationMethod: MigrationMethod = { up: up, down: down };
  export default migrationMethod;
```

## Environment

-   **Node Version**: 14.21.3 
-   **Package Manager Version**: 6.14.18 
-   **Operating System**: linux x64 
-   **contentful**: ^10.8.0
-   **contentful-migration**: ^4.20.1
-   **ts-node**: ^10.9.2
-   **typescript**: ^5.4.3

**Comment by hariprasadr-tw** [comment]
We couldn't reproduce in GitHub Actions workflows pipelines. Hence, closing this issue which due to our environment / network issue.
