### ISSUE TITLE
Communicate "Migration Done!" when it wasn't done - from your docs

### ISSUE THREAD

**Issue by OskarKaminski** [contentful/contentful-migration#145]
If you provide wrong path to the file, you get an error, but anyways runMigration resolve the promise successfully, and you get an info, that everything went fine...

{ Error: Cannot find module './migrations/add-dog-ct'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at run (/Users/oskarkaminski/Documents/projects/ace-website/node_modules/contentful-migration/built/bin/cli.js:40:29)
    at Object.<anonymous> (/Users/oskarkaminski/Documents/projects/ace-website/db/runMigrations.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3) code: 'MODULE_NOT_FOUND' }
Migration Done!

**Comment by Khaledgarbaya** [comment]
This issue had no activity for some time now, please feel free to create a new one if you still have the issue
