### ISSUE TITLE
Migration Library cannot load migration script module

### ISSUE THREAD

**Issue by koriolis** [contentful/contentful-migration#386]
## Expected Behavior
Migration Script runs provided demo code and creates content type dog with field name of type Symbol.

## Actual Behavior
Script errors out with the following message:
```
The migration.js script could not be parsed, as it seems to contain syntax errors.

Error: Cannot find module 'migration.js'
Require stack:
- /mnt/c/dev/contentful/migration/node_modules/contentful-migration/built/bin/cli.js
- /mnt/c/dev/contentful/migration/node_modules/contentful-migration/built/index.js
- /mnt/c/dev/contentful/migration/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at run (/mnt/c/dev/contentful/migration/node_modules/contentful-migration/built/bin/cli.js:50:29)
    at Object.<anonymous> (/mnt/c/dev/contentful/migration/index.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/mnt/c/dev/contentful/migration/node_modules/contentful-migration/built/bin/cli.js',
    '/mnt/c/dev/contentful/migration/node_modules/contentful-migration/built/index.js',
    '/mnt/c/dev/contentful/migration/index.js'
  ]
}
```

## Steps to Reproduce
Followed steps on this projects README file:

1. `npm install contentful-migration`
2. add `index.js` script with:
```
const { runMigration } = require('contentful-migration')

const options = {
  accessToken: '<my-content-management-api-token>',
  spaceId: '<my-space-id>',
  environmentId: '<my-environment-id>',
  yes: true,
  filePath: 'migration.js'
}

runMigration(options)
  .then(() => console.log('Migration Done!'))
  .catch((e) => console.error(e));
```
3. add `migration.js` script with:
```
module.exports = function (migration, context) {
  const dog = migration.createContentType('dog');
  const name = dog.createField('name');
  name.type('Symbol').required(true);
};
```

4. run script with: `node index.js`

## Context
I'm trying to use the migration library to build a script that allows me to merge changes done in one environment into the production environment. This is nothing fancy and it's really what the library was made for. It's frustating to be stopped at the very first step of this project which is running the basic demo code provided.
The scripts don't seem to have any syntax errors (run several linters both on my IDE and manually).
the migration script is in the same folder as the index script so it should be findable (I've tried ./ and / to the name just in case but the result is the same).
I've also tried different versions of NodeJS from 8 to 14 in case there was any issues with breaking chances. The result is the same as above.
At this point I'm out of solutions as to what may cause the issue and hence this issue.

## Environment
-   **Node Version**: v14.3.0
-   **Package Manager Version**: 6.14.5
-   **Operating System**:  Linux KORIOLIS 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
(Windows 10 running WSL Ubuntu distro)
-   **Package Version**: 1.1.3

**Comment by koriolis** [comment]
So after digging around the library source code figured out that a workaround for this issue is to pass an **absolute** filepath instead of relative. So using path it would be something like:
```
filePath: path.join(__dirname, 'migration.js')
```
If this is the general case you can possibly warn in the documentation that filePath needs an absolute path?
