### ISSUE TITLE
Does not execute on windows

### ISSUE THREAD

**Issue by phawxby** [contentful/contentful-migration#695]
`package.json`
```json
{
  "name": "contentful-migration",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "contentful-migration": "^4.0.12",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.2.3"
  }
}
```

Simple to reproduce
```
C:\Users\Z269CJBB\GitHub\contentful-migration>C:\Users\Z269CJBB\GitHub\contentful-migration\node_modules\.bin\ts-node -r tsconfig-paths/register C:\Users\Z269CJBB\GitHub\contentful-migration\node_modules\.bin\contentful-migration
Couldn't find tsconfig.json. tsconfig-paths will be skipped
C:\Users\Z269CJBB\GitHub\contentful-migration\node_modules\.bin\contentful-migration:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at main (C:\Users\Z269CJBB\GitHub\contentful-migration\node_modules\ts-node\src\bin.ts:198:14)
    at Object.<anonymous> (C:\Users\Z269CJBB\GitHub\contentful-migration\node_modules\ts-node\src\bin.ts:288:3)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)

```

**Comment by ilya-orlov** [comment]
@venkatgarlapati have you found a solution for that? It would be really helpful

**Comment by mayakarabula** [comment]
This ticket has been closed due to inactivity. If you still need help resolving your issue, please reach out through our community Slack, or contact Contentful support directly.

**Comment by ozhanefemeral** [comment]
Hi, I am still having the same issue and getting the same error message.

I am simply running the example command (which works completely fine on Mac):

`npx ts-node --skipProject .\node_modules\.bin\contentful-migration -s space_id -e env_id -a access_key .\src\contentful-cms\migrations\my-migration.ts`
